### ISSUE TITLE
[BUG] The cli client doesn't detect the app running

### ISSUE THREAD

**Issue by alba4k** [timschneeb/GalaxyBudsClient#480]
**Describe the bug**  
Trying to use anything from the cli while the app is running will always result in `error: the Galaxy Buds Manager app is not active. The CLI can only be used while the app is running.`

**To Reproduce**  
Run `galaxybudsclient device -G` (example

**Expected behavior**  
Prints what it should print

**Screenshots**  
![immagine](https://github.com/ThePBone/GalaxyBudsClient/assets/84153269/adde59b8-98a5-4fdf-b50c-330694849195)

**Desktop (please complete the following information):**  
 - OS: Arch Linux, fully up-to-date, it_CH, Hyprland
 
 - Application version: 4.6.0

**Additional context**  
-

**Log files**  
-

**Comment by timschneeb** [comment]
This should be fixed in v5.0.0, IPC & the CLI were broken in the last version.
Fixed in the latest version: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.0

**Comment by alba4k** [comment]
Nope, still broken

`galaxybudsclient action -l` works when the buds are not connected, it doesn't when they are connected

![immagine](https://github.com/timschneeb/GalaxyBudsClient/assets/84153269/bbc79b09-8085-47e0-8705-68eaf3e167ad)

**Comment by alba4k** [comment]
It's working now, idk. I'll let you know if it happens again
