### ISSUE TITLE
[CRSH] The provided device ID is not a valid BluetoothDevice object.

### ISSUE THREAD

**Issue by NSQY** [timschneeb/GalaxyBudsClient#513]
Application immediately crashes. No possibility for user interaction.
 
```
[15:02:23 INF] PlatformImpl: Using WindowsRtPlatformImplCreator
[15:02:23 DBG] Windows.HotkeyReceiver: WndProc probes attached
[15:02:23 DBG] WindowsRT.BluetoothService: Device watcher launched
[15:02:23 DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetooth00:e0:4c:31:45:6a-cc:f8:26:0a:6b:c8
[15:02:23 DBG] WindowsRT.BluetoothService: Device updated: Bluetooth#Bluetooth00:e0:4c:31:45:6a-cc:f8:26:0a:6b:c8
[15:02:23 DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetooth10:b1:df:aa:77:40-cc:f8:26:0a:6b:c8
[15:02:23 INF] IpcService: Server listening at tcp:host=::1,port=54533
Unhandled exception. System.ArgumentException: The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
   at GalaxyBudsClient.Platform.WindowsRT.BluetoothService.<.ctor>b__35_4(DeviceWatcher watcher, DeviceInformation deviceInfo)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   ```

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22621.3737
  - Application version: v5.0.0

**Comment by timschneeb** [comment]
The fix has been released in v5.0.1: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.1

**Comment by BoyceXX** [comment]
> The fix has been released in v5.0.1: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.1

Hi Tim, just wanna report here that this issue is unfortunately still there like before. But also thanks for your great work of this APP.

**Comment by NSQY** [comment]
> The fix has been released in v5.0.1: https://github.com/timschneeb/GalaxyBudsClient/releases/tag/5.0.1

I can confirm that this has fixed the issue on my machine, the UI now opens and appears to work as expected. Curiously the same error still appears, though as mentioned this is no longer a tangible issue.

```
[07:42:01 INF] PlatformImpl: Using WindowsRtPlatformImplCreator
[07:42:01 DBG] Windows.HotkeyReceiver: WndProc probes attached
[07:42:01 DBG] WindowsRT.BluetoothService: Device watcher launched
[07:42:01 DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetooth00:e0:4c:31:45:6a-cc:f8:26:0a:6b:c8
[07:42:01 DBG] WindowsRT.BluetoothService: Device updated: Bluetooth#Bluetooth00:e0:4c:31:45:6a-cc:f8:26:0a:6b:c8
[07:42:01 DBG] WindowsRT.BluetoothService: Device added: Bluetooth#Bluetooth10:b1:df:aa:77:40-cc:f8:26:0a:6b:c8
[07:42:01 INF] IpcService: Server listening at tcp:host=::1,port=54533
[07:42:01 ERR] Device info added
System.ArgumentException: The parameter is incorrect.

The provided device ID is not a valid BluetoothDevice object.
   at GalaxyBudsClient.Platform.WindowsRT.BluetoothService.<.ctor>b__35_4(DeviceWatcher watcher, DeviceInformation deviceInfo)
[07:42:02 INF] User script directory: C:\Users\zzz\AppData\Local/GalaxyBudsClient/scripts
[07:42:02 INF] ScriptManager: 0 user script(s) found
[07:42:02 INF] Translator mode file location: C:\Users\zzz\AppData\Local/GalaxyBudsClient/custom_language.xaml
[07:42:02 DBG] Environment: Production
[07:42:02 DBG] Windows.HotkeyReceiver: All hotkeys unregistered
[07:42:02 INF] Startup time: 00:00:01.0210672
[07:42:09 ERR] Failed to parse device ID from SPP service UUID 0146
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
   at GalaxyBudsClient.Model.Specifications.DeviceSpecHelper.FindByDevice(BluetoothDevice device)
[07:42:15 ERR] Failed to parse device ID from SPP service UUID 0146
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
   at GalaxyBudsClient.Model.Specifications.DeviceSpecHelper.FindByDevice(BluetoothDevice device)
[07:42:16 WRN] IDeviceSpec: Cannot compare revision for AmbientExtraLoud. No ExtendedStatusUpdate cached
[07:42:16 WRN] IDeviceSpec: Cannot compare revision for AmbientExtraLoud. No ExtendedStatusUpdate cached
[07:42:16 DBG] WindowsRT.BluetoothService: Selected 'Galaxy Buds2 Pro' (cc:f8:26:0a:6b:c8) from cache as target
[07:42:19 DBG] WindowsRT.BluetoothService: Connected
[07:42:19 DBG] WindowsRT.BluetoothService: Launching BluetoothServiceLoop...
[07:42:19 DBG] Cleaning up old battery stats for cc:f8:26:0a:6b:c8
[07:42:19 WRN] IDeviceSpec: Cannot compare revision for AdvancedTouchLockForCalls. No ExtendedStatusUpdate cached
[07:42:30 DBG] ExperimentRuntime: Launching experiment id #12 (Revision <-> FW version)
[07:42:31 DBG] WindowsRT.BluetoothService: Device enumeration complete
[07:42:31 DBG] ExperimentRuntime: Experiment finished with result code 0
[07:42:31 DBG] ExperimentClient: Posting results for experiment #12...
[07:42:43 DBG] ExperimentRuntime: Launching experiment id #20 (BuildString <-> FW version (New))
[07:42:53 WRN] ExperimentRuntime: Experiment #20 cancelled. Time constraint of 10 seconds exceeded
[07:42:53 DBG] ExperimentRuntime: Experiment finished with result code -2
[07:42:53 DBG] ExperimentClient: Posting results for experiment #20...
[07:42:06 DBG] ExperimentRuntime: Launching experiment id #21 (SKU Values (New))
[07:42:06 ERR] ScriptManager.RegisterHook: Compiler error: <script>(14,36): error CS1061: 'BluetoothImpl' does not contain a definition for 'ActiveModel' and no accessible extension method 'ActiveModel' accepting a first argument of type 'BluetoothImpl' could be found (are you missing a using directive or an assembly reference?)
<script>(15,36): error CS1061: 'BluetoothImpl' does not contain a definition for 'ActiveModel' and no accessible extension method 'ActiveModel' accepting a first argument of type 'BluetoothImpl' could be found (are you missing a using directive or an assembly reference?)

[07:42:06 DBG] ExperimentRuntime: Experiment finished with result code -3
[07:42:06 WRN] ExperimentRuntime: Experiment not unhooked; hook reference is already null
[07:42:06 DBG] ExperimentClient: Posting results for experiment #21...
[07:42:10 DBG] MainWindow.OnClosing: Termination cancelled
```

**Comment by PolarGoose** [comment]
I have encountered the same issue in my project:
https://github.com/PolarGoose/BluetoothDevicePairing/issues/11
